project:
  type: book
  output-dir: _book
book:
  title: Slater Family Cookbook
  author: by Carson and Chloe Slater
  date: today
  chapters:
  - index.qmd
  - chicken-posole-verde.qmd
  - thai-pizza.qmd
  - bourbon-pecan-cherry-hand-pies.qmd
  - toasted-s-more-chocolate-ice-cream-cups.qmd
  - honey-strawberry-muffins.qmd
  - creamy-mocha-custard.qmd
  - skillet-lemon-pepper-chicken-and-garden-veggies.qmd
  - chocolate-dipped-peanut-cookie-ice-cream-sandwiches.qmd
  - chocolate-peanut-butter-honey-cheerio-bars.qmd
  - chocolate-coconut-latte-fudge-popsicles.qmd
  - no-bake-greek-yogurt-fruit-tart.qmd
  - easiest-pistachio-chocolate-baklava.qmd
  - sun-dried-tomato-white-bean-and-goat-cheese-pasta.qmd
  - parchment-baked-lemon-salmon-and-potatoes-with-dill-yogurt.qmd
  - spring-chicken-parmesan-with-tuscan-kale-pesto.qmd
  - whole-wheat-chocolate-chip-skillet-cookie.qmd
  - thai-basil-steak-salad-sandwich-.qmd
  - chipotle-lime-chicken-and-sweet-potato-salad-with-jalape-o-vinaigrette.qmd
  - zucchini-bacon-and-pecorino-tart.qmd
  - spring-skillet-roasted-lemon-chicken-and-veggies.qmd
  - vietnamese-shrimp-spring-roll-bowl-with-sweet-chili-mango-sauce.qmd
  - vibrant-spring-broccoli-buddha-bowl.qmd
  - sun-dried-tomato-and-ricotta-turkey-meatballs.qmd
  - sheet-pan-harissa-chicken-with-chickpeas-and-sweet-potatoes.qmd
  - meal-prep-tropical-jerk-chicken-and-gingered-broccoli.qmd
  - easy-chocolate-heart-doughnuts.qmd
  - browned-butter-sugar-cookie-bars-with-white-chocolate-frosting.qmd
  - roasted-greek-chicken-and-farro-salad-with-fries-.qmd
  - chewy-chocolate-chip-cookie-granola.qmd
  - vegan-whole-wheat-chocolate-chip-banana-bread-muffins.qmd
  - roasted-sweet-potato-and-salmon-soba-noodle-bowl.qmd
  - the-best-everything-spice-egg-avocado-yogurt-bowl.qmd
  - extra-fudgy-ricotta-brownies.qmd
  - quick-cleansing-kale-and-mushroom-pho-.qmd
  - pineapple-margarita-sparklers.qmd
  - seared-scallop-ravioli-with-rosemary-butter-and-lemon-sauce.qmd
  - eggnog-frosted-chai-snickerdoodle-snowmen.qmd
  - cheesy-hasselback-potato-au-gratin.qmd
  - homemade-cheddar-pierogies.qmd
  - buddy-the-elf-cocktail.qmd
  - lemony-fried-brussels-sprouts.qmd
  - the-cheese-maker-s-mac-and-cheese.qmd
  - spinach-and-prosciutto-burrata-calzone.qmd
  - sweet-n-savory-roasted-nuts-and-pretzels.qmd
  - brie-stuffed-crispy-baby-potatoes.qmd
  - cinnamon-streusel-swirled-maple-sweet-potato-casserole.qmd
  - cranberry-thyme-spritz.qmd
  - pomegranate-avocado-salad-with-candied-walnuts.qmd
  - butternut-squash-and-sun-dried-tomato-white-lasagna.qmd
  - easy-flaky-pull-apart-dinner-rolls.qmd
  - honey-butter-roasted-acorn-with-burrata-and-pomegranate.qmd
  - pappardelle-with-roasted-butternut-squash-and-tomato-ragu.qmd
  - pan-roasted-brussels-sprouts-with-bacon-dates-and-halloumi.qmd
  - roasted-cranberry-brown-sugar-pork-chops-.qmd
  - caramelized-garlic-butter-toast-with-pan-fried-mushrooms.qmd
  - roasted-squash-caramelized-fig-and-feta-salad.qmd
  - brussels-sprout-mushroom-pizza-with-crispy-prosciutto-and-sage.qmd
  - pan-roasted-pomegranate-glazed-salmon.qmd
  - healthy-5-ingredient-buckeyes.qmd
  - late-summer-vegetable-bolognese-with-creamy-polenta.qmd
  - chicken-broccoli-quinoa-casserole.qmd
  - lightened-up-salsa-verde-chicken-stuffed-poblano-peppers.qmd
  - easy-3-cup-chicken-with-zucchini-.qmd
  - freezer-friendly-whole-grain-waffles.qmd
  - sneaky-zucchini-mac-and-cheese-with-everything-bagel-chip-crumbs.qmd
  - homemade-blueberry-nutri-grain-bars.qmd
  - sicilian-style-salmon-with-garlic-broccoli-and-tomatoes.qmd
  - pb-j-oat-streusel-muffins.qmd
  - opened-faced-tomato-and-goat-cheese-sandwich-with-hot-bacon-vinaigrette.qmd
  - bourbon-cherry-old-fashioned.qmd
  - blackberry-lavender-white-chocolate-clafoutis.qmd
  - thai-coconut-mussels-with-garlic-lemongrass-toast.qmd
  - raspberry-ginger-stone-fruit-galette.qmd
  - brown-sugar-oatmeal-cookie-cookie-dough-ice-cream-sandwiches.qmd
  - rainbow-thai-basil-noodle-salad-with-sesame-vinaigrette.qmd
  - simple-coconut-mango-chicken-and-broccoli-curry.qmd
  - frozen-cantaloupe-margaritas.qmd
  - mixed-berry-almond-croissants.qmd
  - honey-thyme-and-sweet-cherry-grilled-brie.qmd
  - my-favorite-buttermilk-pie-crust.qmd
  - jalape-o-cheddar-guacamole-turkey-burgers-with-crispy-onions.qmd
  - lemon-feta-dip-with-garlic-tomato-vinaigrette.qmd
  - grilled-thai-satay-chicken.qmd
  - roasted-summer-berry-pi-ata-ice-cream-cake.qmd
  - blueberry-melon-feta-fruit-salad-stacks.qmd
  - farmer-market-pickled-crudit-platter.qmd
  - quick-pickled-veggies.qmd
  - blackberry-lilac-mojito.qmd
  - farmers-market-goat-cheese-pasta-primavera-with-marinated-veggies.qmd
  - honey-strawberry-apricot-tart.qmd
  - greek-roasted-cauliflower-burgers-with-pan-fried-feta-and-tomato-olive-salad.qmd
  - mexican-grilled-corn-with-green-chile-honey-butter.qmd
  - spicy-maple-grilled-chicken-sandwich-with-smoky-bacon-corn.qmd
  - brunch-bruschetta-bar.qmd
  - garden-fresh-herb-olive-and-parmesan-pasta-with-pistachio-breadcrumbs.qmd
  - strawberry-melon-elderflower-pimms-cup.qmd
  - tiramisu-brownie-ice-cream-sandwich-bars.qmd
  - cheesy-zucchini-roasted-corn-tacos-with-mango-salsa-verde.qmd
  - burst-cherry-tomato-artichoke-and-zucchini-pesto-pizza.qmd
  - grilled-corn-and-feta-egg-in-a-hole-avocado-toast.qmd
  - strawberry-cornmeal-cake-with-buttermilk-glaze.qmd
  - lemon-and-oregano-grilled-chicken.qmd
  - rainbow-frozen-yogurt-pops.qmd
  - buttermilk-pancakes-with-chamomile-cream-and-gingered-strawberries.qmd
  - tuscan-steak-with-marinated-cherry-tomatoes.qmd
  - easiest-lemon-ricotta-asparagus-ravioli.qmd
  - layered-zebra-mousse-cake.qmd
  - healthier-oven-fried-sweet-tea-buffalo-chicken-sandwich-.qmd
  - honey-raspberry-brie-crostini-with-basil-oil.qmd
  - spicy-moroccan-fried-eggs.qmd
  - pistachio-rose-rice-pudding.qmd
  - moroccan-pancakes-beghrir-.qmd
  - california-chicken-avocado-and-goat-cheese-salad.qmd
  - island-mango-mezcal-breeze.qmd
  - peanut-butter-swirled-chocolate-fudge-popsicles.qmd
  - breakfast-tacos-al-pastor.qmd
  - greek-lemon-garlic-roasted-broccoli-pasta-salad.qmd
  - cauliflower-rice-carne-asada-bowls-with-mango-salsa.qmd
  - cuban-grilled-salmon-with-tomato-avocado-salsa.qmd
  - strawberry-ripple-almond-cheesecake.qmd
  - cheesy-chipotle-adobo-chicken-quesadillas.qmd
  - easy-lemon-ricotta-old-fashioned-doughnuts.qmd
  - sun-dried-tomato-muhammara-roasted-red-pepper-spread-.qmd
  - blueberry-lemon-poppy-seed-scones.qmd
  - roasted-cauliflower-fried-halloumi-tacos-with-spicy-avocado-basil-guacamole.qmd
  - super-green-pea-and-asparagus-burrata-pizza.qmd
  - morning-glory-power-smoothie.qmd
  - coconut-lime-chicken-curry-with-rice-noodles.qmd
  - crispy-baked-basil-chicken-cordon-bleu.qmd
  - raw-chocolate-banana-cashew-cream-pie-bars.qmd
  - mango-avocado-soba-noodles-with-sesame-salmon-poke.qmd
  - earl-grey-blueberry-oatmeal.qmd
  - easy-broccoli-cheese-tortellini.qmd
  - minty-grapefruit-caipirinha.qmd
  - lighter-shrimp-po-boys-with-avocado-mango-slaw.qmd
  - singapore-sweet-potato-noodles.qmd
  - cuban-style-steak-and-avocado-rice-with-pineapple-chimichurri.qmd
  - mediterranean-roasted-red-pepper-pizza.qmd
  - raspberry-rose-tequila-kombucha-.qmd
  - soft-and-fluffy-cream-cheese-sugar-cookies-.qmd
  - greek-goddess-chicken-lettuce-wraps-.qmd
  - valentine-s-surprise-chocolate-high-hat-cupcakes.qmd
  - glowing-citrus-avocado-quinoa-and-blackened-salmon-salad-.qmd
  - chicken-parmesan-meatball-crostini-.qmd
  - buffalo-cheddar-soft-pretzel-twists-with-everything-spice-.qmd
  - winter-bliss-balls-.qmd
  - orange-turmeric-crush-.qmd
  - chocolate-lovers-greek-yogurt-chocolate-mousse-cake-.qmd
  - healthier-tempeh-reuben-.qmd
  - superfood-cashew-goji-berry-bars-.qmd
  - healthy-chai-banana-pancakes-.qmd
  - spicy-brown-rice-seared-tuna-roll-bowl-with-mango-chimichurri-.qmd
  - herbed-goat-cheese-stuffed-mushrooms-.qmd
  - santa-s-nightcap-.qmd
  - salted-caramel-chocolate-covered-pretzels-.qmd
  - mushroom-cheese-ravioli-with-rosemary-butter-sauce-.qmd
  - christmas-ale-sangria-.qmd
  - chocolate-peanut-butter-crinkle-cookies-.qmd
  - caramelized-balsamic-goat-cheese-pasta-.qmd
  - cheesy-sweet-and-sour-pomegranate-thai-chicken-enchiladas.qmd
  - sugar-cookie-hot-chocolate-.qmd
  - cheese-fondue-board-.qmd
  - crockpot-sun-dried-tomato-penne-alla-vodka-.qmd
  - chocolate-espresso-thumbprint-cookies-.qmd
  - poinsettia-spritz-punch-.qmd
  - spaghetti-and-meatballs-.qmd
  - chocolate-dipped-coconut-caramel-macaroons-.qmd
  - the-north-pole-.qmd
  - crispy-belgian-waffles-.qmd
  - thanksgiving-turkey-hot-dish-.qmd
  - buttery-parker-house-rolls-.qmd
  - turkey-enchilada-quinoa-soup-.qmd
  - butter-pecan-frosted-fudge-brownies-.qmd
  - cranberry-roasted-butternut-persimmon-salad-with-fried-goat-cheese-.qmd
  - cream-of-mushroom-chicken-wild-rice-soup-.qmd
  - buffalo-chicken-dip-sliders.qmd
  - creamy-thai-red-curry-chicken-noodle-soup.qmd
  - crockpot-spicy-queso-beef-chili.qmd
  - pumpkin-beer-pretzels-with-chipotle-queso-.qmd
  - detroit-style-tomato-herb-pepperoni-pizza.qmd
  - pull-apart-cheeseburger-sliders-.qmd
  - crispy-carnitas-tacos-with-roasted-jalape-o-lime-avocado.qmd
  - crockpot-buffalo-chicken-chili.qmd
  - baked-garlic-parmesan-boneless-wings.qmd
  - sheet-pan-honey-buffalo-chicken-with-broccoli.qmd
  - crockpot-chipotle-honey-pot-roast-tacos.qmd
  - pull-apart-roasted-garlic-butter-pizza-dip-sliders.qmd
  - sheet-pan-buffalo-chicken-pizza.qmd
  - crispy-cheesy-sweet-potato-skins.qmd
  - crockpot-crispy-buffalo-chicken-tacos-with-jalape-o-ranch.qmd
  - baked-crunchy-hot-honey-chicken.qmd
  - jalape-o-pepper-jack-cheeseburger-sliders.qmd
  - chipotle-chicken-nachos-with-jalape-o-yogurt.qmd
  - everything-ranch-cheese-and-pretzel-snack-mix.qmd
  - whipped-goat-cheese-candied-bacon-dip.qmd
  - granny-s-7-layer-dip.qmd
  - spinach-and-artichoke-stuffed-soft-pretzels-.qmd
  - hot-honey-pepperoni-pizza-rolls.qmd
  - fried-buffalo-goat-cheese-balls.qmd
  - 3-ingredient-blue-cheese-appetizer.qmd
  - crispy-turmeric-chicken-tenders.qmd
  - sloppy-hot-italian-cheese-dip.qmd
  - 5-ingredient-magic-cookies.qmd
  - really-good-chewy-chocolate-chip-cookies.qmd
  - chocolate-peanut-butter-oatmeal-bars.qmd
  - frosted-brown-butter-snickerdoodle-blondie-bars.qmd
  - homemade-baked-frosted-chocolate-donuts.qmd
  - homemade-hostess-cupcakes-.qmd
  - baked-maple-bacon-doughnuts.qmd
format:
  PrettyPDF-pdf:
    keep-tex: true
    toc: true
    number-sections: false
    classoption: titlepage=false
