# A Liturgy for Feasting with Friends

**Leader:** To gather joyfully is indeed a serious affair, for feasting and all enjoyments gratefully taken are, at their heart, acts of war.

**People:** In celebrating this feast we declare that evil and death, suffering and loss, sorrow and tears, will not have the final word. But the joy of fellowship, and the welcome and comfort of friends new and old, and the celebration of these blessings of food and drink and conversation and laughter are the true evidences of things eternal, and are the first fruits of that great glad joy that is to come and that will be unending.

So let our feast this day be joined to those sure victories secured by Christ. Let it be to us now a delight, and a glad foretaste of his eternal kingdom. Bless us, O Lord, in this feast.

Bless us, O Lord, as we linger over our cups, And over tables laden with good things, as we relish the delights of varied texture and flavor, Of aromas and savory spices, Of dishes prepared as acts of love and blessing, Of sweet delights made sweeter by the communion of saints.

May this shared meal, and our pleasure in it, bear witness against the artifice and deceptions of the prince of the darkness that would blind this world to hope. May it strike at the root of the lie that would drain life of meaning, and the world of joy, and suffering of redemption. May this our feast fall like a great hammer blow against that brittle night, Shattering the gloom, reawakening our hearts, stirring our imaginations, focusing our vision On the kingdom of heaven that is to come On the kingdom that is promised On the kingdom that is already, indeed, among us, For the resurrection of all good things has already joyfully begun.

May this feast be an echo of that great supper of the Lamb, and a foreshadowing of the great celebration that awaits the children of God.

Where two or more of us are gathered, O Lord, there you have promised to be And here we are And so, here are you. Take joy, O King, in this our feast. Take joy, O King!

**Leader:** All will be well!

**People:** All will be well! Nothing good and right and true will be lost forever. All good things will be restored. Feast and be reminded! Take joy, little flock. Take joy! Let battle be joined! Let battle be joined!

Now you who are loved by the Father, prepare your hearts and give yourselves wholly to this celebration of joy, to the glad company of saints, to the comforting fellowship of the Spirit, and to the abiding presence of Christ who is seated among us both as our host and as our honored guest, and still yet as our conquering king. Amen.

In the name of the Father, the Son, and the Holy Spirit, take seat, take feast, take delight!

*Copyright 2016 by Douglas Kaine McKelvey*

