---
title: "Roasted Summer Berry Piñata Ice Cream Cake"
image: ""
---

**Prep Time:** 1 hr | **Cook Time:** 50 min | **Total Time:** 1 hr 50 min

## Ingredients

- 3 cups vanilla ice cream, softened
- 2 1/2 cups all-purpose flour
- 2 teaspoons baking powder
- 1 teaspoon kosher salt
- 2  sticks unsalted butter, at room temperature
- 1 1/4 cups granulated sugar
- 3  whole eggs
- 1 cup buttermilk
- 2 teaspoons vanilla extract
- 3 cups mixed berries, plus fresh berries for serving
- 2 tablespoons honey
- 3  sticks salted butter, at room temperature
- 1 1/2 cups powdered sugar
- 1/2 cup heavy whipping cream
- 2 teaspoons vanilla extract

## Instructions

1. Line one (8 inch) spring form pan with plastic wrap. Spread the ice cream in one even layer. Freeze until firm, 6 hours or overnight. Once Frozen, cut a 10cm round from the center of the cake. Remove center and save for later. Place the ice cream back in the freezer.
1. To make the cake. Preheat the oven to 350 degrees F. Line 2 (8-inch) round cake pans with parchment paper, then grease with butter.
1. In a medium size bowl combine the flour, baking powder and salt. In the bowl of a stand mixer (or use a hand-held mixer) beat together the butter and sugar until light and fluffy. With the mixer on low, beat in the eggs. Add the vanilla and beat until combined. Slowly add the dry ingredients to the wet ingredients with the mixer on low, alternating with the buttermilk and ending with flour until just combined.
1. Pour the batter among the cake pans and bake 25-30 minutes, until the tops are just set and no longer wiggly in the center. Remove and let cool five minutes, then turn the cakes out onto a rack to cool further. To one of the cakes, cut a 10cm round from the center. Remove the center and discard. Keep the remaining cake layer whole. Freeze the cakes until frozen, at least 2 hours.
1. To make the berries. Preheat the oven to 400 degrees F. In a 9x13 inch baking dish, combine the berries and honey. Transfer to the oven and roast for 15-20 minutes or until the berries have burst and released their juice. Let cool.
1. To make the buttercream. Add the butter and powdered sugar to the bowl of a stand mixer. Beat the butter and powdered sugar together until the butter is light and fluffy. Add the vanilla and continue beating, scraping down the sides as needed, for another 2 minutes. Add the heavy cream and whip the frosting for 2-4 minutes more or until light and fluffy.
1. To assemble the cake. Lay the vanilla cake layer, the one with the hole cut out of the center, flat on a serving plate. Spread with buttercream over the cake, then add half roasted berries over the buttercream. Add the ice cream cake layer and again, spread the buttercream over the ice cream and inside the hole. Spread the remaining roasted berries on top of the buttercream ice cream layer. Freeze 2 hours or until firm.
1. Remove the cake from the freezer and fill the hole with fresh berries. Now add the remaining vanilla cake layer and frost the cake all over with the remaining buttercream. Freeze another 2 hours or until firm. Just before serving, decorate the top of the cake with berries. Slice and enjoy!

